// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZHwL4n3ier1gewZKAkc8f3R1y_3N10Fs',
    appId: '1:888079860458:android:71ba289626ea4af65e0d93',
    messagingSenderId: '888079860458',
    projectId: 'exam-saathi-student',
    storageBucket: 'exam-saathi-student.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKzLPn6ck1K9ySE6qtJI8-o2SquQrDLgo',
    appId: '1:888079860458:web:02e199bbfed62e665e0d93',
    messagingSenderId: '888079860458',
    projectId: 'exam-saathi-student',
    authDomain: 'exam-saathi-student.firebaseapp.com',
    storageBucket: 'exam-saathi-student.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.examsaathi.app',
  );
}